#pi=3.14
#print(pi)
#pi=input("Digite o valor de pi: ")
#print(type(pi)
#nota=int(input("Digite uma nota entre 0 e 10: "))
#print(type(nota))
usuario=input("Digite o seu nome: ")
print("qual o tipo?", type(usuario))
print("Tem numeros?", usuario.isnumeric())
print("Tem letras?", usuario.isalpha())
print("Esta em caixa Alta?", usuario.isupper())
print("Esta em caixa baixa?", usuario.islower())
#print("Divida em dois", usuario.split("."))